# Generated by Django 4.1.5 on 2023-02-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winners',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.myuser', verbose_name='Победитель'),
        ),
    ]
